//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class agnesPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="SWIGRegisterExceptionCallbacks_agnes")]
    public static extern void SWIGRegisterExceptionCallbacks_agnes(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_agnes")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_agnes(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_agnes(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_agnes(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="SWIGRegisterStringCallback_agnes")]
    public static extern void SWIGRegisterStringCallback_agnes(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_agnes(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  public class SWIGStringWithLengthHelper {

    [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="SWIG_csharp_string_to_c")]
    private static extern global::System.IntPtr SWIG_csharp_string_to_c0(int size, int len, [global::System.Runtime.InteropServices.In,global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr, SizeParamIndex=0)] string str);

    [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="SWIG_csharp_string_size")]
    private static extern int SWIG_csharp_string_size(global::System.IntPtr str);

    [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="SWIG_csharp_string_str")]
    private static extern global::System.IntPtr SWIG_csharp_string_str(global::System.IntPtr str);

    public static global::System.IntPtr SWIG_csharp_string_to_c(string str) {
      if (str == null)
        return global::System.IntPtr.Zero;
      global::System.Text.Encoding utf8 = global::System.Text.Encoding.UTF8;
      return SWIG_csharp_string_to_c0(utf8.GetByteCount(str), str.Length, str);
    }

    public static string SWIG_c_to_csharp_string(global::System.IntPtr str) {
      int size = SWIG_csharp_string_size(str);
      if (size > 0) {
        global::System.IntPtr s = SWIG_csharp_string_str(str);
        byte[] b = new byte[size];
        global::System.Runtime.InteropServices.Marshal.Copy(s, b, 0, size);
        global::System.Text.Encoding utf8 = global::System.Text.Encoding.UTF8;
        return utf8.GetString(b);
      }
      return null;
    }
  }


  static agnesPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="SWIG_csharp_bytes_to_c")]
  public static extern global::System.IntPtr SWIG_csharp_bytes_to_c0(int len, byte[] ptr);
  public static global::System.IntPtr SWIG_csharp_bytes_to_c(byte[] ptr) {
    return SWIG_csharp_bytes_to_c0(ptr.Length, ptr);
  }


  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="SWIG_csharp_data")]
  public static extern int SWIG_csharp_data(global::System.IntPtr data, ref global::System.IntPtr m);


  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_cdata")]
  public static extern global::System.IntPtr cdata(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_memmove")]
  public static extern void memmove(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_AGNES_VERSION_MAJOR_get")]
  public static extern int AGNES_VERSION_MAJOR_get();

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_AGNES_VERSION_MINOR_get")]
  public static extern int AGNES_VERSION_MINOR_get();

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_AGNES_VERSION_PATCH_get")]
  public static extern int AGNES_VERSION_PATCH_get();

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_AGNES_VERSION_STRING_get")]
  public static extern string AGNES_VERSION_STRING_get();

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_AGNES_SCREEN_WIDTH_get")]
  public static extern int AGNES_SCREEN_WIDTH_get();

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_AGNES_SCREEN_HEIGHT_get")]
  public static extern int AGNES_SCREEN_HEIGHT_get();

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_input_t_a_set")]
  public static extern void agnes_input_t_a_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_input_t_a_get")]
  public static extern bool agnes_input_t_a_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_input_t_b_set")]
  public static extern void agnes_input_t_b_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_input_t_b_get")]
  public static extern bool agnes_input_t_b_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_input_t_select_set")]
  public static extern void agnes_input_t_select_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_input_t_select_get")]
  public static extern bool agnes_input_t_select_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_input_t_start_set")]
  public static extern void agnes_input_t_start_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_input_t_start_get")]
  public static extern bool agnes_input_t_start_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_input_t_up_set")]
  public static extern void agnes_input_t_up_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_input_t_up_get")]
  public static extern bool agnes_input_t_up_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_input_t_down_set")]
  public static extern void agnes_input_t_down_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_input_t_down_get")]
  public static extern bool agnes_input_t_down_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_input_t_left_set")]
  public static extern void agnes_input_t_left_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_input_t_left_get")]
  public static extern bool agnes_input_t_left_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_input_t_right_set")]
  public static extern void agnes_input_t_right_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_input_t_right_get")]
  public static extern bool agnes_input_t_right_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_new_agnes_input_t")]
  public static extern global::System.IntPtr new_agnes_input_t();

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_delete_agnes_input_t")]
  public static extern void delete_agnes_input_t(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_color_t_r_set")]
  public static extern void agnes_color_t_r_set(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_color_t_r_get")]
  public static extern byte agnes_color_t_r_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_color_t_g_set")]
  public static extern void agnes_color_t_g_set(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_color_t_g_get")]
  public static extern byte agnes_color_t_g_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_color_t_b_set")]
  public static extern void agnes_color_t_b_set(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_color_t_b_get")]
  public static extern byte agnes_color_t_b_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_color_t_a_set")]
  public static extern void agnes_color_t_a_set(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_color_t_a_get")]
  public static extern byte agnes_color_t_a_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_new_agnes_color_t")]
  public static extern global::System.IntPtr new_agnes_color_t();

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_delete_agnes_color_t")]
  public static extern void delete_agnes_color_t(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_make")]
  public static extern global::System.IntPtr agnes_make();

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_destroy")]
  public static extern void agnes_destroy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_load_ines_data")]
  public static extern bool agnes_load_ines_data(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_set_input")]
  public static extern void agnes_set_input(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_state_size")]
  public static extern uint agnes_state_size();

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_dump_state")]
  public static extern void agnes_dump_state(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_restore_state")]
  public static extern bool agnes_restore_state(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_tick")]
  public static extern bool agnes_tick(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_next_frame")]
  public static extern bool agnes_next_frame(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_get_screen_pixel")]
  public static extern global::System.IntPtr agnes_get_screen_pixel(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_read_file")]
  public static extern global::System.IntPtr agnes_read_file(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("agnes", EntryPoint="CSharp_agnes_load_ines_data_from_path")]
  public static extern bool agnes_load_ines_data_from_path(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);
}
