/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040301
#define SWIGCSHARP

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 *
 * Note that SWIG expects __cplusplus to be defined to the appropriate C++ standard.
 * MSVC users are urged to check and examine the /Zc:__cplusplus compiler option.
 * See https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_agnes(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_agnes(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_agnes(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } } while (0)


typedef struct SWIGCDATA {
  char *data;
  size_t len;
} SWIGCDATA;






static SWIGCDATA cdata_void(void *ptr, size_t nelements)



{
  SWIGCDATA d;
  d.data = (char *) ptr;



  d.len  = nelements;

   return d;
}





#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT int SWIGSTDCALL SWIG_csharp_data(SWIGCDATA *d, void **ptr) {
  int ret = 0;
  if (d != SWIG_NULLPTR) {
    if (d->len > 0 && d->data != SWIG_NULLPTR) {
      *ptr = (void *)d->data;
      ret = (int)d->len;
    }
    free(d); /* allocated in 'out' typemap */
  }
  return ret;
}

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif
typedef struct { int len; void *ptr; } SWIG_csharp_bytes;

SWIGEXPORT void *SWIGSTDCALL SWIG_csharp_bytes_to_c(int len, void *ptr) {
  SWIG_csharp_bytes *ret = (SWIG_csharp_bytes *)malloc(sizeof(SWIG_csharp_bytes));
  if (ret == SWIG_NULLPTR) {
    SWIG_CSharpSetPendingException(SWIG_CSharpOutOfMemoryException, "fail to duplicate bytes container.");
    return SWIG_NULLPTR;
  }
  if (len > 0) {
    ret->ptr = malloc(len);
    if (ret->ptr == SWIG_NULLPTR) {
      SWIG_CSharpSetPendingException(SWIG_CSharpOutOfMemoryException, "fail to duplicate bytes.");
      free(ret);
      return SWIG_NULLPTR;
    }
    memcpy(ret->ptr, ptr, len);
    ret->len = len;
  } else {
    ret->ptr = SWIG_NULLPTR;
    ret->len = 0;
  }
  return ret;
}

#ifdef __cplusplus
}
#endif


#include <stdint.h>		// Use the C99 official header


/* Includes the header in the wrapper code */
#include "agnes.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT SWIGCDATA * SWIGSTDCALL CSharp_cdata(void * jarg1, unsigned int jarg2) {
  SWIGCDATA * jresult ;
  void *arg1 = (void *) 0 ;
  size_t arg2 = (size_t) 1 ;
  SWIGCDATA result;
  
  arg1 = (void *)jarg1; 
  arg2 = (size_t)jarg2; 
  result = cdata_void(arg1,arg2);
  
  jresult = (SWIGCDATA*)malloc(sizeof(result));
  if (jresult != SWIG_NULLPTR) {
    memcpy(jresult, &result, sizeof(result));
  }
  
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_memmove(void * jarg1, void * jarg2) {
  void *arg1 = (void *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  
  arg1 = (void *)jarg1; 
  {
    SWIG_csharp_bytes *p = (SWIG_csharp_bytes *)jarg2;
    if (p != SWIG_NULLPTR) {
      arg2 = (void *)p->ptr;
      arg3 = (size_t)p->len;
    } else {
      arg2 = 0;
      arg3 = 0;
    }
  }
  memmove(arg1,(void const *)arg2,arg3);
  {
    SWIG_csharp_bytes *p = (SWIG_csharp_bytes *)jarg2;
    if (p != SWIG_NULLPTR) {
      free(p->ptr);
      free(p);
    }
  }
}


SWIGEXPORT int SWIGSTDCALL CSharp_AGNES_VERSION_MAJOR_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_AGNES_VERSION_MINOR_get() {
  int jresult ;
  int result;
  
  result = (int)(2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_AGNES_VERSION_PATCH_get() {
  int jresult ;
  int result;
  
  result = (int)(0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_AGNES_VERSION_STRING_get() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)("0.2.0");
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_AGNES_SCREEN_WIDTH_get() {
  int jresult ;
  int result;
  
  result = (int)AGNES_SCREEN_WIDTH;
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_AGNES_SCREEN_HEIGHT_get() {
  int jresult ;
  int result;
  
  result = (int)AGNES_SCREEN_HEIGHT;
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_agnes_input_t_a_set(void * jarg1, unsigned int jarg2) {
  agnes_input_t *arg1 = (agnes_input_t *) 0 ;
  bool arg2 ;
  
  arg1 = (agnes_input_t *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->a = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_agnes_input_t_a_get(void * jarg1) {
  unsigned int jresult ;
  agnes_input_t *arg1 = (agnes_input_t *) 0 ;
  bool result;
  
  arg1 = (agnes_input_t *)jarg1; 
  result = (bool) ((arg1)->a);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_agnes_input_t_b_set(void * jarg1, unsigned int jarg2) {
  agnes_input_t *arg1 = (agnes_input_t *) 0 ;
  bool arg2 ;
  
  arg1 = (agnes_input_t *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->b = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_agnes_input_t_b_get(void * jarg1) {
  unsigned int jresult ;
  agnes_input_t *arg1 = (agnes_input_t *) 0 ;
  bool result;
  
  arg1 = (agnes_input_t *)jarg1; 
  result = (bool) ((arg1)->b);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_agnes_input_t_select_set(void * jarg1, unsigned int jarg2) {
  agnes_input_t *arg1 = (agnes_input_t *) 0 ;
  bool arg2 ;
  
  arg1 = (agnes_input_t *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->select = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_agnes_input_t_select_get(void * jarg1) {
  unsigned int jresult ;
  agnes_input_t *arg1 = (agnes_input_t *) 0 ;
  bool result;
  
  arg1 = (agnes_input_t *)jarg1; 
  result = (bool) ((arg1)->select);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_agnes_input_t_start_set(void * jarg1, unsigned int jarg2) {
  agnes_input_t *arg1 = (agnes_input_t *) 0 ;
  bool arg2 ;
  
  arg1 = (agnes_input_t *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->start = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_agnes_input_t_start_get(void * jarg1) {
  unsigned int jresult ;
  agnes_input_t *arg1 = (agnes_input_t *) 0 ;
  bool result;
  
  arg1 = (agnes_input_t *)jarg1; 
  result = (bool) ((arg1)->start);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_agnes_input_t_up_set(void * jarg1, unsigned int jarg2) {
  agnes_input_t *arg1 = (agnes_input_t *) 0 ;
  bool arg2 ;
  
  arg1 = (agnes_input_t *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->up = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_agnes_input_t_up_get(void * jarg1) {
  unsigned int jresult ;
  agnes_input_t *arg1 = (agnes_input_t *) 0 ;
  bool result;
  
  arg1 = (agnes_input_t *)jarg1; 
  result = (bool) ((arg1)->up);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_agnes_input_t_down_set(void * jarg1, unsigned int jarg2) {
  agnes_input_t *arg1 = (agnes_input_t *) 0 ;
  bool arg2 ;
  
  arg1 = (agnes_input_t *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->down = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_agnes_input_t_down_get(void * jarg1) {
  unsigned int jresult ;
  agnes_input_t *arg1 = (agnes_input_t *) 0 ;
  bool result;
  
  arg1 = (agnes_input_t *)jarg1; 
  result = (bool) ((arg1)->down);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_agnes_input_t_left_set(void * jarg1, unsigned int jarg2) {
  agnes_input_t *arg1 = (agnes_input_t *) 0 ;
  bool arg2 ;
  
  arg1 = (agnes_input_t *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->left = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_agnes_input_t_left_get(void * jarg1) {
  unsigned int jresult ;
  agnes_input_t *arg1 = (agnes_input_t *) 0 ;
  bool result;
  
  arg1 = (agnes_input_t *)jarg1; 
  result = (bool) ((arg1)->left);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_agnes_input_t_right_set(void * jarg1, unsigned int jarg2) {
  agnes_input_t *arg1 = (agnes_input_t *) 0 ;
  bool arg2 ;
  
  arg1 = (agnes_input_t *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->right = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_agnes_input_t_right_get(void * jarg1) {
  unsigned int jresult ;
  agnes_input_t *arg1 = (agnes_input_t *) 0 ;
  bool result;
  
  arg1 = (agnes_input_t *)jarg1; 
  result = (bool) ((arg1)->right);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_agnes_input_t() {
  void * jresult ;
  agnes_input_t *result = 0 ;
  
  result = (agnes_input_t *)calloc(1, sizeof(agnes_input_t));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_agnes_input_t(void * jarg1) {
  agnes_input_t *arg1 = (agnes_input_t *) 0 ;
  
  arg1 = (agnes_input_t *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_agnes_color_t_r_set(void * jarg1, unsigned char jarg2) {
  agnes_color_t *arg1 = (agnes_color_t *) 0 ;
  uint8_t arg2 ;
  
  arg1 = (agnes_color_t *)jarg1; 
  arg2 = (uint8_t)jarg2; 
  if (arg1) (arg1)->r = arg2;
}


SWIGEXPORT unsigned char SWIGSTDCALL CSharp_agnes_color_t_r_get(void * jarg1) {
  unsigned char jresult ;
  agnes_color_t *arg1 = (agnes_color_t *) 0 ;
  uint8_t result;
  
  arg1 = (agnes_color_t *)jarg1; 
  result = (uint8_t) ((arg1)->r);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_agnes_color_t_g_set(void * jarg1, unsigned char jarg2) {
  agnes_color_t *arg1 = (agnes_color_t *) 0 ;
  uint8_t arg2 ;
  
  arg1 = (agnes_color_t *)jarg1; 
  arg2 = (uint8_t)jarg2; 
  if (arg1) (arg1)->g = arg2;
}


SWIGEXPORT unsigned char SWIGSTDCALL CSharp_agnes_color_t_g_get(void * jarg1) {
  unsigned char jresult ;
  agnes_color_t *arg1 = (agnes_color_t *) 0 ;
  uint8_t result;
  
  arg1 = (agnes_color_t *)jarg1; 
  result = (uint8_t) ((arg1)->g);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_agnes_color_t_b_set(void * jarg1, unsigned char jarg2) {
  agnes_color_t *arg1 = (agnes_color_t *) 0 ;
  uint8_t arg2 ;
  
  arg1 = (agnes_color_t *)jarg1; 
  arg2 = (uint8_t)jarg2; 
  if (arg1) (arg1)->b = arg2;
}


SWIGEXPORT unsigned char SWIGSTDCALL CSharp_agnes_color_t_b_get(void * jarg1) {
  unsigned char jresult ;
  agnes_color_t *arg1 = (agnes_color_t *) 0 ;
  uint8_t result;
  
  arg1 = (agnes_color_t *)jarg1; 
  result = (uint8_t) ((arg1)->b);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_agnes_color_t_a_set(void * jarg1, unsigned char jarg2) {
  agnes_color_t *arg1 = (agnes_color_t *) 0 ;
  uint8_t arg2 ;
  
  arg1 = (agnes_color_t *)jarg1; 
  arg2 = (uint8_t)jarg2; 
  if (arg1) (arg1)->a = arg2;
}


SWIGEXPORT unsigned char SWIGSTDCALL CSharp_agnes_color_t_a_get(void * jarg1) {
  unsigned char jresult ;
  agnes_color_t *arg1 = (agnes_color_t *) 0 ;
  uint8_t result;
  
  arg1 = (agnes_color_t *)jarg1; 
  result = (uint8_t) ((arg1)->a);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_agnes_color_t() {
  void * jresult ;
  agnes_color_t *result = 0 ;
  
  result = (agnes_color_t *)calloc(1, sizeof(agnes_color_t));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_agnes_color_t(void * jarg1) {
  agnes_color_t *arg1 = (agnes_color_t *) 0 ;
  
  arg1 = (agnes_color_t *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_agnes_make() {
  void * jresult ;
  agnes_t *result = 0 ;
  
  result = (agnes_t *)agnes_make();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_agnes_destroy(void * jarg1) {
  agnes_t *arg1 = (agnes_t *) 0 ;
  
  arg1 = (agnes_t *)jarg1; 
  agnes_destroy(arg1);
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_agnes_load_ines_data(void * jarg1, void * jarg2, unsigned int jarg3) {
  unsigned int jresult ;
  agnes_t *arg1 = (agnes_t *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  bool result;
  
  arg1 = (agnes_t *)jarg1; 
  arg2 = (void *)jarg2; 
  arg3 = (size_t)jarg3; 
  result = (bool)agnes_load_ines_data(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_agnes_set_input(void * jarg1, void * jarg2, void * jarg3) {
  agnes_t *arg1 = (agnes_t *) 0 ;
  agnes_input_t *arg2 = (agnes_input_t *) 0 ;
  agnes_input_t *arg3 = (agnes_input_t *) 0 ;
  
  arg1 = (agnes_t *)jarg1; 
  arg2 = (agnes_input_t *)jarg2; 
  arg3 = (agnes_input_t *)jarg3; 
  agnes_set_input(arg1,(agnes_input_t const *)arg2,(agnes_input_t const *)arg3);
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_agnes_state_size() {
  unsigned int jresult ;
  size_t result;
  
  result = agnes_state_size();
  jresult = (unsigned int)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_agnes_dump_state(void * jarg1, void * jarg2) {
  agnes_t *arg1 = (agnes_t *) 0 ;
  agnes_state_t *arg2 = (agnes_state_t *) 0 ;
  
  arg1 = (agnes_t *)jarg1; 
  arg2 = (agnes_state_t *)jarg2; 
  agnes_dump_state((struct agnes const *)arg1,arg2);
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_agnes_restore_state(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  agnes_t *arg1 = (agnes_t *) 0 ;
  agnes_state_t *arg2 = (agnes_state_t *) 0 ;
  bool result;
  
  arg1 = (agnes_t *)jarg1; 
  arg2 = (agnes_state_t *)jarg2; 
  result = (bool)agnes_restore_state(arg1,(struct agnes_state const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_agnes_tick(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  agnes_t *arg1 = (agnes_t *) 0 ;
  bool *arg2 = (bool *) 0 ;
  bool result;
  
  arg1 = (agnes_t *)jarg1; 
  arg2 = (bool *)jarg2; 
  result = (bool)agnes_tick(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_agnes_next_frame(void * jarg1) {
  unsigned int jresult ;
  agnes_t *arg1 = (agnes_t *) 0 ;
  bool result;
  
  arg1 = (agnes_t *)jarg1; 
  result = (bool)agnes_next_frame(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_agnes_get_screen_pixel(void * jarg1, int jarg2, int jarg3) {
  void * jresult ;
  agnes_t *arg1 = (agnes_t *) 0 ;
  int arg2 ;
  int arg3 ;
  agnes_color_t result;
  
  arg1 = (agnes_t *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = agnes_get_screen_pixel((struct agnes const *)arg1,arg2,arg3);
  {
    agnes_color_t * resultptr = (agnes_color_t *) malloc(sizeof(agnes_color_t));
    memmove(resultptr, &result, sizeof(agnes_color_t));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_agnes_read_file(char * jarg1, void * jarg2) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  size_t *arg2 = (size_t *) 0 ;
  void *result = 0 ;
  
  arg1 = (char *)jarg1; 
  arg2 = (size_t *)jarg2; 
  result = (void *)agnes_read_file((char const *)arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_agnes_load_ines_data_from_path(void * jarg1, char * jarg2) {
  unsigned int jresult ;
  agnes_t *arg1 = (agnes_t *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  
  arg1 = (agnes_t *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (bool)agnes_load_ines_data_from_path(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

