//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class agnes_input_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal agnes_input_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(agnes_input_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(agnes_input_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~agnes_input_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          agnesPINVOKE.delete_agnes_input_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool a {
    set {
      agnesPINVOKE.agnes_input_t_a_set(swigCPtr, value);
    } 
    get {
      bool ret = agnesPINVOKE.agnes_input_t_a_get(swigCPtr);
      return ret;
    } 
  }

  public bool b {
    set {
      agnesPINVOKE.agnes_input_t_b_set(swigCPtr, value);
    } 
    get {
      bool ret = agnesPINVOKE.agnes_input_t_b_get(swigCPtr);
      return ret;
    } 
  }

  public bool select {
    set {
      agnesPINVOKE.agnes_input_t_select_set(swigCPtr, value);
    } 
    get {
      bool ret = agnesPINVOKE.agnes_input_t_select_get(swigCPtr);
      return ret;
    } 
  }

  public bool start {
    set {
      agnesPINVOKE.agnes_input_t_start_set(swigCPtr, value);
    } 
    get {
      bool ret = agnesPINVOKE.agnes_input_t_start_get(swigCPtr);
      return ret;
    } 
  }

  public bool up {
    set {
      agnesPINVOKE.agnes_input_t_up_set(swigCPtr, value);
    } 
    get {
      bool ret = agnesPINVOKE.agnes_input_t_up_get(swigCPtr);
      return ret;
    } 
  }

  public bool down {
    set {
      agnesPINVOKE.agnes_input_t_down_set(swigCPtr, value);
    } 
    get {
      bool ret = agnesPINVOKE.agnes_input_t_down_get(swigCPtr);
      return ret;
    } 
  }

  public bool left {
    set {
      agnesPINVOKE.agnes_input_t_left_set(swigCPtr, value);
    } 
    get {
      bool ret = agnesPINVOKE.agnes_input_t_left_get(swigCPtr);
      return ret;
    } 
  }

  public bool right {
    set {
      agnesPINVOKE.agnes_input_t_right_set(swigCPtr, value);
    } 
    get {
      bool ret = agnesPINVOKE.agnes_input_t_right_get(swigCPtr);
      return ret;
    } 
  }

  public agnes_input_t() : this(agnesPINVOKE.new_agnes_input_t(), true) {
  }

}
