//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class agnes_color_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal agnes_color_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(agnes_color_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(agnes_color_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~agnes_color_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          agnesPINVOKE.delete_agnes_color_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public byte r {
    set {
      agnesPINVOKE.agnes_color_t_r_set(swigCPtr, value);
    } 
    get {
      byte ret = agnesPINVOKE.agnes_color_t_r_get(swigCPtr);
      return ret;
    } 
  }

  public byte g {
    set {
      agnesPINVOKE.agnes_color_t_g_set(swigCPtr, value);
    } 
    get {
      byte ret = agnesPINVOKE.agnes_color_t_g_get(swigCPtr);
      return ret;
    } 
  }

  public byte b {
    set {
      agnesPINVOKE.agnes_color_t_b_set(swigCPtr, value);
    } 
    get {
      byte ret = agnesPINVOKE.agnes_color_t_b_get(swigCPtr);
      return ret;
    } 
  }

  public byte a {
    set {
      agnesPINVOKE.agnes_color_t_a_set(swigCPtr, value);
    } 
    get {
      byte ret = agnesPINVOKE.agnes_color_t_a_get(swigCPtr);
      return ret;
    } 
  }

  public agnes_color_t() : this(agnesPINVOKE.new_agnes_color_t(), true) {
  }

}
